strictness: veryhigh
doc-warnings: true
member-warnings: false
test-warnings: false

ignore-patterns:
  - (^|/)\..+
  - .*\.html
  - docs/.*
  - tmp\.py
  - setup\.py
  - hubspot3\/test\/.*

pylint:
  disable:
    - bad-continuation
    - broad-except
    - import-error
    - import-self
    - logging-format-interpolation
    - logging-fstring-interpolation
    - missing-docstring
    - no-self-use
    - unused-argument
    - protected-access
    - cyclic-import
    - import-outside-toplevel
    - unnecessary-comprehension
    - unsubscriptable-object
    # TODO the one below should be removed after some time
    - super-with-arguments

  options:
    max-args: 12
    max-locals: 100
    max-returns: 6
    max-branches: 50
    max-statements: 180
    max-parents: 10
    max-attributes: 10
    min-public-methods: 0
    max-public-methods: 40
    max-module-lines: 2000
    max-line-length: 100

mccabe:
  options:
    max-complexity: 30

pycodestyle:
  disable:
    - N802
    - N807
    - N813
    - N818
    - W503
    - W605
    - E203
  options:
    max-line-length: 100
    single-line-if-stmt: n

vulture:
  run: false

pyroma:
  run: false

bandit:
  run: false

pydocstyle:
  disable:
    - D000
    - D100
    - D101
    - D102
    - D103
    - D104
    - D105
    - D107
    - D200
    - D202
    - D203
    - D204
    - D205
    - D212
    - D300
    - D400
    - D401
    - D403
    - D404
    - D407
    - D411
    - D413
    - D415
    - D416
    - D417

pyflakes:
  disable:
    - F401
    - F403
    - F999
