---
apiVersion: v1
kind: Pod
metadata:
  name: apptest
spec:
  serviceAccountName: aplazame-appdeployer
  serviceAccount: aplazame-appdeployer
  securityContext:
    fsGroup: 1000
  containers:
    - name: sonar
      image: 666356151544.dkr.ecr.eu-central-1.amazonaws.com/tools/sonar-scanner:4.6.2.2472_2
      imagePullPolicy: Always
      tty: true
      resources:
        limits:
          cpu: 1
          memory: 3Gi
  restartPolicy: Never