name: test

on: [push]

jobs:
  prospector:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: jpetrucciani/prospector-check@master
  mypy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: jpetrucciani/mypy-check@master
  black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: jpetrucciani/black-check@master
        with:
          path: 'hubspot3/'
  tests:
    runs-on: ubuntu-20.04
    needs: [mypy, prospector, black]
    strategy:
      matrix:
        # '3.6', '3.7', '3.8', - need to figure out how to get around rate limiting
        python-version: ['3.9']
    name: python ${{ matrix.python-version }} tests
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: install requirements
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: run Tox
        run: tox -e py
